//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEQLDB.ServiceModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int id { get; set; }
        public string name { get; set; }
        public string phoneNumber { get; set; }
        public string notes { get; set; }
        public Nullable<bool> myFavourite { get; set; }
        public Nullable<bool> gender { get; set; }
        public Nullable<int> idNetWork { get; set; }
    
        public virtual Network Network { get; set; }
    }
}
