//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEQLDB.ServiceModel
{
    using ServiceStack;
    using System;
    using System.Collections.Generic;

    public partial class Network
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Network()
        {
            this.Contacts = new HashSet<Contact>();
        }

        public int id { get; set; }
        public string nameNetwork { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contact> Contacts { get; set; }
    }

    [Route("/networks", "GET")]
    public class GetNetWork : IReturn<BaseResponse>
    {
        public string nameNetwork { get; set; }
    }

    [Route("/networks", "POST")]
    public class CreateNetwork : IReturn<BaseResponse>
    {
        public string nameNetwork { get; set; }
    }

    [Route("/networks/{id}", "PUT")]
    public class UpdateNetwork : IReturn<BaseResponse>
    {
        public int Id { get; set; }
        public string nameNetwork { get; set; }
    }

    [Route("/networks/{id}", "DELETE")]
    public class NetworkById : IReturn<BaseResponse>
    {
        public int Id { get; set; }
    }
}
